Use codeup_test_db;

TRUNCATE albums;

INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Michael Jackson','Thriller',1982,46,'Pop, rock, R&B');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('AC/DC','Back in Black',1980,26.1,'Hard rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Pink Floyd','The Dark Side of the Moon',1973,24.2,'Progressive rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Whitney Houston / Various artists','The Bodyguard',1992,27.4,'Soundtrack/R&B, soul, pop');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Meat Loaf','Bat Out of Hell',1977,20.6,'Hard rock, progressive rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Eagles','Their Greatest Hits (1971–1975)',1976,32.2,'Rock, soft rock, folk rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Bee Gees / Various artists','Saturday Night Fever',1977,20.6,'Disco');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Fleetwood Mac','Rumours',1977,27.9,'Soft rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Shania Twain','Come On Over',1997,29.6,'Country, pop');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Led Zeppelin','Led Zeppelin IV',1971,29,'Hard rock, heavy metal');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Michael Jackson','Bad',1987,20.3,'Pop, funk, rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Alanis Morissette','Jagged Little Pill',1995,24.8,'Alternative rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Celine Dion','Falling into You',1996,20.2,'Pop, Soft rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('The Beatles','Sgt. Pepper''s Lonely Hearts Club Band',1967,13.1,'Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Eagles','Hotel California',1976,21.5,'Rock, soft rock, folk rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Mariah Carey','Music Box',1993,19,'Pop, R&B, Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Michael Jackson','Dangerous',1991,17.6,'Rock, Funk, Pop');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Various artists','Dirty Dancing',1987,17.9,'Pop, rock, R&B');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Celine Dion','Let''s Talk About Love',1997,19.3,'Pop, Soft rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('The Beatles','1',2000,21.6,'Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Adele','21',2011,22.3,'Pop, soul');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('The Beatles','Abbey Road',1969,14.4,'Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Bruce Springsteen','Born in the U.S.A.',1984,19.6,'Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Dire Straits','Brothers in Arms',1985,17.7,'Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('James Horner','Titanic: Music from the Motion Picture',1997,18.1,'Soundtrack');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Madonna','The Immaculate Collection',1990,19.4,'Pop, Dance');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Metallica','Metallica',1991,19.9,'Thrash metal, heavy metal');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Nirvana','Nevermind',1991,16.7,'Grunge, alternative rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Pink Floyd','The Wall',1979,17.6,'Progressive rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Santana','Supernatural',1999,20.5,'Rock');
INSERT INTO albums (`artist`,`name`,`release_date`,`sales`,`genre`) VALUES('Guns N'' Roses','Appetite for Destruction',1987,21.3,'Heavy metal, hard rock');